language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: seB9gAep45Tii82hJd/NJw8aFQ5nZ+c5T1h7+YBio6/5jUt5/0bXwk4x43SoIDW8mJEONFZ7LnH0YjbuWpuBhqNGDpPozXGopLClxvLDeVr+CzqhxFyoQi4cp0q9XXIR6855rGVSFEBLpC1psMAZrf0roZHwHmrix96YtqpEY8grg7fvPKNtdNkbCm9JEQ/rTr/oUXV3Am9FaSP5Ytwk39y686UTe0+TbITNs1HPuKt8MC2Sji5ssTPLg+N8UOKvIvo3mfqnzVXpkfOU9axmElTyWhLIMP4BsJwiMl8e8npKtLGbENQBQPnH57hT8qd58gILOEHNzBI6E65avt3lpCN57utcz6McG8Dzx+kfsRSPEsPpX3GJtwYGEZcMQk3EMc/LuyKYXuv7wVlzC61iaAcPWDG3c0MQsXMjqVPhinQ371390GAHrJF2Ee3nb3sebv96s/f76Z8sfTfDwN3qtmmQgKshoAk9W1ahwV80gmfIUtCzBxIgdSBmCqa5IUbw2pTNaPZd3EWe9TwUXqw7r2rZ400s1xd8+O+lwv93jTDs5J5/MxgAAD/NE03p5aAn9cOl141tnFAwbEd5UbkpTE2nhyaLJKrpQceuZ3yUFF8br4Iry40u0UnpCyIn7lxku7WFmut8W+XhvcA/L1aH0DidJvPSBDFSTgteoaacjEM=
  app: recipe-savor
  skip_cleanup: true